apiVersion: v1
kind: Service
metadata:
  name: {{ include "my_eks_k8s_cluster_charts.fullname" . }}
  labels:
    {{- include "my_eks_k8s_cluster_charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my_eks_k8s_cluster_charts.selectorLabels" . | nindent 4 }}
